config/routes.rb
Rails.application.routes.draw do

  resources :bands
  resources :venues
  resources :concerts

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, :presence => true
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  has_many :bands
  validates :bands, :presence => true
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :name, :presence => true
  validates :city, :presence => true
  validates :country, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.create(params.require(:band).permit(:name, :country))
    @band.save!
    redirect_to bands_path
  end

  def edit
    @band = Band.where(:id => params[:id]).first
  end

  def update
    @band = Band.where(:id => params[:id]).first
    @band.update_attributes(params.require(:band).permit(:name, :country))
    @band.save!
    redirect_to bands_path
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  def index
    @concerts = Concert.all
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venues_path, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to venues_path, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params[:venue].permit(:name, :country, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/bands/_form.html.erb
<%= form_for @band do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :country %>
  <%= f.text_field :country %>

  <%= f.submit %>
<% end %>

app/views/bands/edit.html.erb
<h1>Create new band</h1>
<%= render "form" %>

app/views/bands/index.html.erb
<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, edit_band_path(band) %> (<%= band.country %>)</li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>Create new band</h1>
<%= render "form" %>

app/views/concerts/index.html.erb
<h1>List of concerts</h1>

<table>
  <thead>
    <tr>
      <td><%= t('.date') %></td>
      <td><%= t('.bands') %></td>
      <td><%= t('.city') %></td>
      <td><%= t('.country') %></td>
    </tr>
  </thead>
  <% @concerts.each do |concert| %>
    <tr>
      <td><%= concert.date %></td>
      <td><%= concert.bands.first.name %></td>
      <td><%= concert.city %></td>
      <td><%= concert.country %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bands</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :city %>
    <%= f.text_field :city %>
    <%= f.label :country %>
    <%= f.text_field :country %>

    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <td><%= t('.name') %></td>
      <td><%= t('.city') %></td>
      <td><%= t('.country') %></td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.city %></td>
        <td><%= venue.country %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>